name: CORTX reviewdog
on:  
  pull_request_target:
    branches:
      - main
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: nightly
      - name: "Install Alex"
        run: |
          npm install alex --global
      - name: "Review dog"
        run: |
          reviewdog -efm="%f:%l:%c: %m" -diff="git diff FETCH_HEAD"
