name: CORTX reviewdog
on:  
  pull_request_target:
    types: [opened] 
    branches:
      - main
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.TOKEN }}
          pr-message: |-
              Congrats on working with cortx
