name: CORTX reviewdog
on:  
  workflow_run:
    workflows: ["Dispatch event for Alex"]
    types: [completed]
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    # if: ${{ github.event.label.name == 'cla-signed' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    env:
      #GITHUB_REF: refs/pull/31/merge
      CI_PULL_REQUEST: 33
      CI_COMMIT: ${{ github.event.workflow_run.head_commit.id }}
      CI_REPO_OWNER: seagate
      CI_REPO_NAME: alex-test
      #GITHUB_SHA: ${{ github.event.workflow_run.head_commit.id }}
    steps:
      - uses: actions/checkout@v2
      - name: See commit sha on head branch
        run: echo ${{ github.event.workflow_run.head_commit.id }}
      - name: see whole payload
        run: echo "${{ toJSON(github.event.workflow_run) }}"
      
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added
          reporter: github-check
          fail_on_error: false
