name: CORTX reviewdog
on:  
  pull_request_review_comment:
    branches:
      - main
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: venkuppu-chn/action-alex-nightly@v2.0.1
        with:
          github_token: $TOKEN
          filter_mode: added
          reporter: github-pr-review
          fail_on_error: false
        env:
          TOKEN: ${{ secrets.TOKEN }}
