name: CORTX reviewdog
on:  
  pull_request:
    types: [labeled]
    branches:
      - main
  workflow_dispatch:  
jobs:
  alex:
    name: Scan and report the inclusive words
    if: ${{ github.event.label.name == 'bug' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          filter_mode: added
          reporter: github-pr-check
          fail_on_error: false
