name: Dispatch event for Alex
on:
  pull_request_target:
    branches:
      - main
jobs:  
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          event-type: alex-event
