name: CORTX reviewdog
on:  
  workflow_run:
    workflows: ["Dispatch event for Alex"]
    types: [completed]
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    # if: ${{ github.event.label.name == 'cla-signed' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: See commit sha on head branch
        run: echo ${{ github }}
      
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added
          reporter: github-check
          fail_on_error: false
