name: CORTX reviewdog
on:  
  pull_request_target:
    types: [opened] 
    branches:
      - main
  workflow_dispatch:
jobs:
  alex:
    name: Scan and report the inclusive words
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.TOKEN }}
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          filter_mode: added
          reporter: github-pr-review
          fail_on_error: false
