name: CI notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  alex:
    name: Scan and report the inclusive words
    # if: ${{ github.event.label.name == 'cla-signed' || github.event.action == 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: added
          reporter: github-pr-review
          fail_on_error: false
		  
