name: "Workflow"
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - name: "PR checklist"
        uses: "venkuppu-chn/cortx-pr-checklist@v1.3"
        
